export const TAB_URL_TO_PLAIN = 'TAB_URL_TO_PLAIN'
export const TAB_URL_TO_MARKDOWN = 'TAB_URL_TO_MARKDOWN'
export const TAB_URL_TO_HTML = 'TAB_URL_TO_HTML'
export const TAB_URL_TO_BBCODE = 'TAB_URL_TO_BBCODE'

export const FRAME_URL_TO_PLAIN = 'FRAME_URL_TO_PLAIN'
export const FRAME_URL_TO_MARKDOWN = 'FRAME_URL_TO_MARKDOWN'
export const FRAME_URL_TO_HTML = 'FRAME_URL_TO_HTML'
export const FRAME_URL_TO_BBCODE = 'FRAME_URL_TO_BBCODE'

export const LINK_TO_MARKDOWN = 'LINK_TO_MARKDOWN'
export const LINK_TO_HTML = 'LINK_TO_HTML'
export const LINK_TO_BBCODE = 'LINK_TO_BBCODE'

export const SELECTION_TO_MARKDOWN = 'SELECTION_TO_MARKDOWN'

export const SELECTION_TO_HTML = 'SELECTION_TO_HTML'
export const SELECTION_TO_HTML_ONLY_A_TAG = 'SELECTION_TO_HTML_ONLY_A_TAG'
export const SELECTION_TO_HTML_NO_ATTR = 'SELECTION_TO_HTML_NO_ATTR'

export const SELECTION_TO_BBCODE = 'SELECTION_TO_BBCODE'
export const SELECTION_TO_PLAIN = 'SELECTION_TO_PLAIN'
export const SELECTION_TO_PLAIN_TRIMMED = 'SELECTION_TO_PLAIN_TRIMMED'
export const SELECTION_TO_RAW_STRING = 'SELECTION_TO_RAW_STRING'

export const IMAGE_TO_MARKDOWN = 'IMAGE_TO_MARKDOWN'
export const IMAGE_TO_MARKDOWN_DATA_URI_JPEG = 'IMAGE_TO_MARKDOWN_DATA_URI_JPEG'
export const IMAGE_TO_MARKDOWN_DATA_URI_PNG = 'IMAGE_TO_MARKDOWN_DATA_URI_PNG'
export const IMAGE_TO_MARKDOWN_DATA_URI_WEBP = 'IMAGE_TO_MARKDOWN_DATA_URI_WEBP'

export const IMAGE_TO_HTML = 'IMAGE_TO_HTML'
export const IMAGE_TO_HTML_DATA_URI_JPEG = 'IMAGE_TO_HTML_DATA_URI_JPEG'
export const IMAGE_TO_HTML_DATA_URI_PNG = 'IMAGE_TO_HTML_DATA_URI_PNG'
export const IMAGE_TO_HTML_DATA_URI_WEBP = 'IMAGE_TO_HTML_DATA_URI_WEBP'

export const IMAGE_TO_BBCODE = 'IMAGE_TO_BBCODE'

export const IMAGE_TO_DATA_URI_RAW = 'IMAGE_TO_DATA_URI_RAW'
export const IMAGE_TO_DATA_URI_JPEG = 'IMAGE_TO_DATA_URI_JPEG'
export const IMAGE_TO_DATA_URI_PNG = 'IMAGE_TO_DATA_URI_PNG'
export const IMAGE_TO_DATA_URI_WEBP = 'IMAGE_TO_DATA_URI_WEBP'

export const AUDIO_TO_HTML = 'AUDIO_TO_HTML'
export const VIDEO_TO_HTML = 'VIDEO_TO_HTML'
